### ISSUE TITLE
feature request: --round option to N decimal places

### ISSUE THREAD

**Issue by avilella** [agordon/datamash#5]
Would it be possible to add '--round N' option to datamash so that the values coming out of the calculations are rounded to a certain number of decimal places? Thx

**Comment by agordon** [comment]
Hello @avilella,

The latest version (in git, soon to be released) contains new operations: round, floor, ceil, trunc, frac - hopefully these would do what you asked:

       The following demonstrate the different rounding operations:
       $ ( echo X ; seq -1.25 0.25 1.25 ) \
             | datamash --full -H round 1 ceil 1 floor 1 trunc 1 frac 1

         X     round(X)  ceil(X)  floor(X)  trunc(X)   frac(X)
       -1.25   -1        -1       -2        -1         -0.25
       -1.00   -1        -1       -1        -1          0
       -0.75   -1         0       -1         0         -0.75
       -0.50   -1         0       -1         0         -0.5
       -0.25    0         0       -1         0         -0.25
        0.00    0         0        0         0          0
        0.25    0         1        0         0          0.25
        0.50    1         1        0         0          0.5
        0.75    1         1        0         0          0.75
        1.00    1         1        1         1          0
        1.25    1         2        1         1          0.25

**Comment by sskarkhanis** [comment]
I second that...it would be really great to have the '--round N' feature to datamash...
currently , I have to use an awk work around

if it's easier/quicker, it would be great if datamash by default rounds to 2/3 digits of a number when using any of the stat functions mean, median etc

**Comment by agordon** [comment]
Two years later... but better late than never.

**Comment by fungs** [comment]
Just a quick question: does the round only apply to the raw input or is it possible to round the outcome of, for instance, mean? Or in more general terms, is it possible to chain operations?

**Comment by agordon** [comment]
The `round` operation rounds the input values.
The `-R/--round=N` command-line argument rounds the output.
In datamash version 1.3 there is also a new option `--format` where you can specify a custom printf-like output, e.g.:
```
$ echo '50.5' | datamash --format "%07.3f" sum 1
050.500
```

Generally, it is highly recommended to send all questions, commends, requests and bug-reports to the `bug-datamash@gnu.org` mailing list (there is no need to subscribe first if you don't want to).
