### ISSUE TITLE
datamash unable to work with float values and exponential values 

### ISSUE THREAD

**Issue by thisek** [agordon/datamash#7]
hi,

I want to use datamash in text file which contains float values and exponential values in separate columns but unfortunately program throws an error saying non-numeric field. 
Do you have any suggestion to make datamash work on decimal values and exponential values?

**Comment by agordon** [comment]
Hello @thisek,

Can you provide an example of your input ? what do you mean by "exponential" values?
Please also show the complete command you are using and the exact error message shown.

**Comment by agordon** [comment]
With no further responses, I'm closing this issue for now.
