### ISSUE TITLE
Last datamash and Ubuntu14. Problem with gettext version

### ISSUE THREAD

**Issue by annuskeras** [agordon/datamash#8]
The last datamash version, the one that includes trimmean, it is not compatible with the last version of gettext available for Ubuntu 14.06.
That's the error message when trying to run ./bootstrup : 

> ./bootstrap: Error: 'autopoint' version == 0.18.3 is too old
> ./bootstrap:        'autopoint' version >= 0.19.4 is required
> ./bootstrap: Error: 'gettext' version == 0.18.3 is too old
> ./bootstrap:        'gettext' version >= 0.19.4 is required
> ./bootstrap: 221: ./bootstrap: gperf: not found
> ./bootstrap: Error: 'gperf' not found
> ./bootstrap: Error: 'pkg-config' version == 0.26 is too old
> ./bootstrap:        'pkg-config' version >= 0.28 is required

**Comment by agordon** [comment]
Hello @annuskeras 

The simplest work around is to download the development tar archive that includes this feature:
  https://download-mirror.savannah.gnu.org/releases/datamash/datamash-1.2.6-46fb.tar.gz
And running the usual `./configure && make && sudo make install`.

When building from `git` and using `bootstrap`, it is assumed the builder is a developer who has recent development tools. Ubuntu 14 is from 2014 - 3 years old and contain 3-years old tools.

When building from tar archive, development tools such as 'autopoint' are not required, and the build should "just work" even on very old systems.

regards,
 gordon
